import Head from "next/head";
import useCalculators from "../lib/hooks/useCalculators";

export default function Home() {
  const { calculators } = useCalculators();

  return (
    <>
      <Head>
        <title>알 빠진 주판</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {calculators.map((item) => (
          <div key={item.name}>
            <h3>{item.name}</h3>
            <p>{item.description}</p>
          </div>
        ))}
      </main>
    </>
  );
}
